[package]
name = "iron-seatbelt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.1"
nom_locate = "4.0.0"
rstest = "0.16.0"

[dev-dependencies]
textwrap = "0.16.0"
